import fs from 'node:fs';
import path from 'node:path';

// Project-owned custom theme generation; other presets use the shared engine.
export function generateCustomDesign(root, design, args) {
  if (args.some(arg => arg !== '--check')) throw new Error('custom design accepts only --check');
  const source = path.resolve(root, design.stylesheet);
  if (!source.startsWith(root + path.sep)) throw new Error('Stylesheet must stay within the project');
  const target = path.join(root, 'docs/guide/assets/docflow-design.css');
  const css = fs.readFileSync(source, 'utf8').replaceAll('\r\n', '\n').trimEnd();
  if (!css.trim()) throw new Error('Custom stylesheet is empty');
  const header = `/* Generated from ${design.stylesheet}. Do not edit this file.\n * Regenerate: node tools/docgen/common.mjs design\n */\n`;
  const expected = header + css + '\n';
  if (args.includes('--check')) {
    if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8').replaceAll('\r\n', '\n') !== expected) {
      throw new Error('Generated design differs. Run node tools/docgen/common.mjs design');
    }
    console.log('디자인 생성 결과 일치');
  } else {
    fs.mkdirSync(path.dirname(target), {recursive: true});
    fs.writeFileSync(target, expected);
    console.log('문서 디자인 적용: custom');
  }
}
