created: 2026-09-09T16:09:56.205Z
updated: 2026-09-19T10:03:12.342Z
update_count: 5
last_field: description
kind: nested-class
title: screens
children:
  - benchmark-screen
  - cts-screen
  - expert-screen
  - gallery-screen
  - look-tokens
  - probe-screen
parentPath: []
