created: 2026-09-09T16:09:56.205Z
updated: 2026-09-14T12:23:53.025Z
update_count: 5
last_field: description
kind: nested-class
title: screens
children:
  - benchmark-screen
  - expert-screen
  - look-tokens
parentPath: []
