created: 2026-09-09T16:12:29.474Z
updated: 2026-09-14T12:24:19.635Z
update_count: 3
last_field: description
kind: nested-class
title: telemetry
children:
  - capture-callbacks
  - flight-recorder
  - incident-exporter
parentPath: []
