created: 2026-09-09T16:18:30.377Z
updated: 2026-09-19T10:02:54.177Z
update_count: 5
last_field: description
kind: nested-class
title: persistence
children:
  - benchmark-report
  - benchmark-store
parentPath: []
