created: 2026-09-17T00:00:00.000Z
updated: 2026-09-19T10:03:37.593Z
update_count: 2
last_field: description
kind: nested-class
title: capture-cases
children: []
parentPath:
  - screens
  - cts-screen
