created: 2026-09-09T16:13:31.458Z
updated: 2026-09-09T16:13:41.316Z
update_count: 2
last_field: diagram
kind: nested-class
title: check-runner
children:
  - check-evaluator
  - check-result
  - check-state-machine
  - endpoint-model
  - endpoint-resolver
parentPath: []
