created: 2026-09-16T04:00:00.000Z
updated: 2026-09-17T01:00:00.000Z
update_count: 3
last_field: description
kind: nested-class
title: cts-screen
children:
  - capture-cases
  - case-runtime
  - on-off-cases
  - recording-case
  - vendored-cases
parentPath:
  - screens
