created: 2026-09-09T16:11:25.751Z
updated: 2026-09-09T16:12:19.095Z
update_count: 3
last_field: constraint
kind: nested-class
title: camera-engines
children:
  - camera2-engine
  - camerax-engine
  - endpoint-model
  - endpoint-resolver
  - engine-interface
parentPath: []
